### PR TITLE
Remove signed update system entirely

### LINKED ISSUE #11: ursa-purejs
Moving to ursa-purejs form ursa caused problems. So I had to roll it back. We should use the pure js version if possible.

### PR DESCRIPTION
**Pull request by yousefamar**
The point of assymetric crypto was for the CM to be able to prove authorship to the arbiter by signing updates. This commit makes the CM instead use the key/token system that everything else uses. The key is passed to the arbiter as an environment variable just as it is for other containers. Since we use HTTPS for all connections to the arbiter, the keys are protected as they are passed with requests. Resolves #11.

Code and docs in Hypercat branch in arbiter will be updated to reflect this.

### CODE REVIEW

**Comment by Toshbrown** [comment]
Hi @yousefamar,

Should there be some changes to the arbiter to go with this? It seems to break things when I merge it. 

Cheers

Tosh

**Comment by yousefamar** [comment]
> Should there be some changes to the arbiter to go with this?

Yes,
> Code and docs in Hypercat branch in arbiter will be updated to reflect this.

I'll PR those soon.

>  It seems to break things when I merge it.

Ah, looks like you pushed stuff directly to the Hypercat branch in the meantime since I made that PR. I'll try to rebase and untangle things then I'll comment here when done.

**Comment by yousefamar** [comment]
Instead of rebasing then force pushing to my fork, I merged my changes to yours, then just made the Hypercat branch on my fork track that. Was a little more painful than I expected; I'm not too good with merge tools. :D

Could you check if everything still works before merging this PR? I'll PR arbiter changes in a moment. From now on could we have the Hypercat branch be like master and only PR to it instead of directly pushing?

**Comment by Toshbrown** [comment]
All working. Thanks ;-)

**Pull request merged**
